# Generated by Django 4.1.7 on 2025-04-07 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAnswers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('securityAnswer1', models.CharField(blank=True, max_length=255, null=True)),
                ('securityAnswer2', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
