# Generated by Django 4.1.7 on 2025-04-07 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='date_received',
        ),
        migrations.RemoveField(
            model_name='income',
            name='source',
        ),
    ]
