# Generated by Django 4.1.7 on 2025-04-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_remove_income_date_received_remove_income_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_income',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='who_what',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
