# Generated by Django 4.1.7 on 2025-04-07 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_remove_transaction_description_transaction_is_income_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='who_what',
            new_name='with_who_or_what',
        ),
    ]
