# Generated by Django 4.1.7 on 2025-04-07 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_rename_who_what_transaction_with_who_or_what'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='is_income',
            new_name='type',
        ),
    ]
